### PR TITLE
Update CodeTrophs

### PR DESCRIPTION
**Pull request by aryasoni98**
Update codeTrophs project on Leaderboard

### CODE REVIEW

**Comment by praveenscience** [comment]
Waiting for approvals from @Vishal-raj-1 and @salil-naik.

**Comment by Vishal-raj-1** [comment]
@aryasoni98 are you a Contributor or PA. If you are not Contributor, then why did you add your name in that file. ?

**Comment by aryasoni98** [comment]
@Vishal-raj-1 I'm project admin ( PA ) . I just forgot. I will edit the file .

**Review by praveenscience — CHANGES_REQUESTED** [review]
Thanks, three projects are added to the Leaderboard. 🔥

**Review by praveenscience — APPROVED** [review]
Thanks, three projects are added to the Leaderboard. 🔥

**Pull request merged**
