### PR TITLE
project sakura contributors repo added

### PR DESCRIPTION
**Pull request by ArunTeltia**
@praveenscience can you merge this, i have added one more repo in my organization in which participants are contributing to it

### CODE REVIEW

**Comment by praveenscience** [comment]
Waiting for approvals from @Vishal-raj-1 and @salil-naik.

**Comment by ArunTeltia** [comment]
I have already added this repo in the gssoc projects

**Comment by salil-naik** [comment]
> Waiting for approvals from @Vishal-raj-1 and @salil-naik.

Merge the PR @praveenscience

**Review by praveenscience — APPROVED** [review]
Merging 👍

**Pull request merged**
